// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: detection.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - signalq.DetectionService

/// Namespace containing generated types for the "signalq.DetectionService" service.
internal enum Signalq_DetectionService {
    /// Service descriptor for the "signalq.DetectionService" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "signalq.DetectionService")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "SendDetection" metadata.
        internal enum SendDetection {
            /// Request type for "SendDetection".
            internal typealias Input = Signalq_Detection
            /// Response type for "SendDetection".
            internal typealias Output = Signalq_Acknowledgement
            /// Descriptor for "SendDetection".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "signalq.DetectionService"),
                method: "SendDetection"
            )
        }
        /// Descriptors for all methods in the "signalq.DetectionService" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            SendDetection.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "signalq.DetectionService" service.
    internal static let signalq_DetectionService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "signalq.DetectionService")
}

// MARK: signalq.DetectionService (server)

extension Signalq_DetectionService {
    /// Streaming variant of the service protocol for the "signalq.DetectionService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "SendDetection" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Signalq_Detection` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Signalq_Acknowledgement` messages.
        func sendDetection(
            request: GRPCCore.StreamingServerRequest<Signalq_Detection>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Signalq_Acknowledgement>
    }

    /// Service protocol for the "signalq.DetectionService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: Signalq_DetectionService.StreamingServiceProtocol {
        /// Handle the "SendDetection" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Signalq_Detection` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Signalq_Acknowledgement` message.
        func sendDetection(
            request: GRPCCore.ServerRequest<Signalq_Detection>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Signalq_Acknowledgement>
    }

    /// Simple service protocol for the "signalq.DetectionService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: Signalq_DetectionService.ServiceProtocol {
        /// Handle the "SendDetection" method.
        ///
        /// - Parameters:
        ///   - request: A `Signalq_Detection` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Signalq_Acknowledgement` to respond with.
        func sendDetection(
            request: Signalq_Detection,
            context: GRPCCore.ServerContext
        ) async throws -> Signalq_Acknowledgement
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Signalq_DetectionService.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Signalq_DetectionService.Method.SendDetection.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Signalq_Detection>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Signalq_Acknowledgement>(),
            handler: { request, context in
                try await self.sendDetection(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Signalq_DetectionService.ServiceProtocol {
    internal func sendDetection(
        request: GRPCCore.StreamingServerRequest<Signalq_Detection>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Signalq_Acknowledgement> {
        let response = try await self.sendDetection(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Signalq_DetectionService.SimpleServiceProtocol {
    internal func sendDetection(
        request: GRPCCore.ServerRequest<Signalq_Detection>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Signalq_Acknowledgement> {
        return GRPCCore.ServerResponse<Signalq_Acknowledgement>(
            message: try await self.sendDetection(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: signalq.DetectionService (client)

extension Signalq_DetectionService {
    /// Generated client protocol for the "signalq.DetectionService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "SendDetection" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Signalq_Detection` message.
        ///   - serializer: A serializer for `Signalq_Detection` messages.
        ///   - deserializer: A deserializer for `Signalq_Acknowledgement` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func sendDetection<Result>(
            request: GRPCCore.ClientRequest<Signalq_Detection>,
            serializer: some GRPCCore.MessageSerializer<Signalq_Detection>,
            deserializer: some GRPCCore.MessageDeserializer<Signalq_Acknowledgement>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Signalq_Acknowledgement>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "signalq.DetectionService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SendDetection" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Signalq_Detection` message.
        ///   - serializer: A serializer for `Signalq_Detection` messages.
        ///   - deserializer: A deserializer for `Signalq_Acknowledgement` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func sendDetection<Result>(
            request: GRPCCore.ClientRequest<Signalq_Detection>,
            serializer: some GRPCCore.MessageSerializer<Signalq_Detection>,
            deserializer: some GRPCCore.MessageDeserializer<Signalq_Acknowledgement>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Signalq_Acknowledgement>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Signalq_DetectionService.Method.SendDetection.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Signalq_DetectionService.ClientProtocol {
    /// Call the "SendDetection" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Signalq_Detection` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func sendDetection<Result>(
        request: GRPCCore.ClientRequest<Signalq_Detection>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Signalq_Acknowledgement>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.sendDetection(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Signalq_Detection>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Signalq_Acknowledgement>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Signalq_DetectionService.ClientProtocol {
    /// Call the "SendDetection" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func sendDetection<Result>(
        _ message: Signalq_Detection,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Signalq_Acknowledgement>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Signalq_Detection>(
            message: message,
            metadata: metadata
        )
        return try await self.sendDetection(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}